app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('test/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
    path('cal/', include('cal.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from django.conf.urls import url

app_name = 'pages'

urlpatterns = [
    #path('', views.index, name='index'), 
    path('dashboard/', views.dashboard, name='dashboard'), 
    #path('home/', views.home, name='home'),    
    #path('register', views.register, name='register'),
    #path('login', views.login, name='login'),
    path('calendar/', views.calendar, name='calendar'),
    path('shoppinglist/<int:list_id>/', views.shopping_list, name='shoppingList'),
    path('plan-create/', views.plan_generate, name='plancreate'),
    path('mealplanview/', views.mealplan_view, name='mealplanView'),
    url(r'ajax/dismiss_shopping_list_item/$', views.dismiss_shopping_list_item, name='dismiss_item'),
    url(r'ajax/lock_status/$', views.meal_plan_lock_status, name='meal_plan_lock_status'),
    url(r'ajax/remove_shopping_list/$', views.remove_shopping_list, name='remove_shopping_list'),
    url(r'ajax/generate_shopping_list/$', views.generate_shopping_list, name='generate_shopping_list'),
    url(r'ajax/feedback_meal/$', views.feedback_meal, name='feedback_meal'),

]

templates/partials/_add_to_mealplan.html
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">Add to Meal Plan</h5>
        
    </div>
    <div class="card-body">
        <form action="{% url 'recipe' recipe.id %}" method="POST">
            {%csrf_token%}
            <label for="date"> Date for?</label>
            <input class="form-control" type="date" id="date" name="date"><br>

            <label for="meal"> Select Meal </label><br> 
            <select class="form-control" name="meal" id="meal">
                <option value="BREAKFAST">Breakfast</option>
                <option value="MORNING_SNACK">Morning Snack</option>
                <option value="LUNCH">Lunch</option>
                <option value="AFTERNOON_SNACK">Afternoon Snack</option>
                <option value="DINNER">Dinner</option>
                <option value="EVENING_SNACK">Late Snack</option>
            </select> <br>
            <input type="hidden" name="recipeId" id="recipeId" value="{{recipe.id}}">
            <button class="btn btn-primary" id="submit" type="submit">Submit form</button>
        </form>
        
    </div>
    <div class="card-footer">
        <div class="row align-items-center">
            <div class="col">
                <span class="h6 mb-0 avatar-content">You're using this in the next 14 days: </span>
            </div>
        </div>
        <ul class="list-group">
            {% for futureMeal in futureMeals%}
            <li class="list-group-item">{{futureMeal.start}}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="card-footer">
        <div class="row align-items-center">
            <div class="col">
                <span class="h6 mb-0 avatar-content">You've used this in the last 14 days: </span>
            </div>
        </div>
        <ul class="list-group">
            {% for pastMeal in pastMeals%}
            <li class="list-group-item">{{pastMeal.start}}</li>
            {% endfor %}
        </ul>
    </div>
    
</div>

templates/partials/_billing.html
      <!-- Page content -->
      <div class="page-content">
        <div class="min-vh-100 py-5 d-flex align-items-center">
          <div class="w-100">
            <div class="row justify-content-center">
              <div class="col-sm-8 col-lg-5">
                <div class="card shadow zindex-100 mb-0">
                  <div class="card-body px-md-5 py-5">
                    <div class="mb-5">
                      <h6 class="h3">Create account</h6>
                      <p class="text-muted mb-0">Made with love by developers for developers.</p>
                    </div>
                    <span class="clearfix"></span>
                    <form role="form">
                      <div class="form-group">
                        <label class="form-control-label">Email address</label>
                        <div class="input-group input-group-merge">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                          </div>
                          <input type="email" class="form-control" id="input-email" placeholder="name@example.com">
                        </div>
                      </div>
                      <div class="form-group mb-4">
                        <label class="form-control-label">Password</label>
                        <div class="input-group input-group-merge">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                          </div>
                          <input type="password" class="form-control" id="input-password" placeholder="********">
                          <div class="input-group-append">
                            <span class="input-group-text">
                              <a href="#" data-toggle="password-text" data-target="#input-password">
                                <i class="fas fa-eye"></i>
                              </a>
                            </span>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="form-control-label">Confirm password</label>
                        <div class="input-group input-group-merge">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                          </div>
                          <input type="password" class="form-control" id="input-password-confirm" placeholder="********">
                        </div>
                      </div>
                      <div class="my-4">
                        <div class="custom-control custom-checkbox mb-3">
                          <input type="checkbox" class="custom-control-input" id="check-terms">
                          <label class="custom-control-label" for="check-terms">I agree to the <a href="#">terms and conditions</a></label>
                        </div>
                        <div class="custom-control custom-checkbox">
                          <input type="checkbox" class="custom-control-input" id="check-privacy">
                          <label class="custom-control-label" for="check-privacy">I agree to the <a href="#">privacy policy</a></label>
                        </div>
                      </div>
                      <div class="mt-4"><button type="button" class="btn btn-sm btn-primary btn-icon rounded-pill">
                          <span class="btn-inner--text">Create my account</span>
                          <span class="btn-inner--icon"><i class="fas fa-long-arrow-alt-right"></i></span>
                        </button></div>
                    </form>
                  </div>
                  <div class="card-footer px-md-5"><small>Already have an acocunt?</small>
                    <a href="#" class="small font-weight-bold">Sign in</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer -->
    </div>
  </div>
  <!-- Scripts -->
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="../../assets/js/purpose.core.js"></script>
  <!-- Purpose JS -->
  <script src="../../assets/js/purpose.js"></script>
  <!-- Demo JS - remove it when starting your project -->
  <script src="../../assets/js/demo.js"></script>
</body>

</html>

templates/partials/_calendar.html
<div class="page-content">
  <div class="page-title">
    <div class="row justify-content-between align-items-center">
      <div class="col d-flex align-items-center">
        <a
          href="#"
          class="text-white pr-3"
          data-toggle="tooltip"
          data-placement="left"
          data-original-title="Go back"
          ><i class="fas fa-angle-left"></i
        ></a>
        <h5
          class="fullcalendar-title h4 d-inline-block font-weight-400 mb-0 text-white"
        >
          Calendar
        </h5>
      </div>
      <div class="col-lg-6 mt-3 mt-lg-0 text-lg-right">
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="#" class="fullcalendar-btn-prev btn btn-sm btn-neutral">
            <i class="fas fa-angle-left"></i>
          </a>
          <a href="#" class="fullcalendar-btn-next btn btn-sm btn-neutral">
            <i class="fas fa-angle-right"></i>
          </a>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="#" class="btn btn-sm btn-neutral" data-calendar-view="month"
            >Month</a
          >
          <a
            href="#"
            class="btn btn-sm btn-neutral"
            data-calendar-view="basicWeek"
            >Week</a
          >
          <a
            href="#"
            class="btn btn-sm btn-neutral"
            data-calendar-view="basicDay"
            >Day</a
          >
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <!-- Fullcalendar -->
      <div class="card overflow-hidden">
        <div class="calendar" data-toggle="calendar" id="calendar"></div>
      </div>
      <!-- Modal - Add new event -->
      <!--* Modal header *-->
      <div
        class="modal fade custom_cl"
        id="new-event"
        tabindex="-1"
        role="dialog"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
              <form class="new-event--form" >
              
           
                <div class="form-group">
                  <label class="form-control-label">Event title</label>
                  <input
                    type="text"
                    class="form-control form-control-alternative new-event--title"
                    placeholder="Event Title" name="name" id="name"
                  />
                </div>
                <div class="form-group">
                  <label for="exampleFormControlSelect1">MealPosition:</label>
                  <select name="mealPosition" class="form-control" id="exampleFormControlSelect1">
                  <option value="BREAKFAST">BREAKFAST</option>
                  <option value="MORNING_SNACK">MORNING SNACK</option>
                  <option value="LUNCH">LUNCH</option>
                  <option value="AFTERNOON_SNACK">AFTERNOON SNACK</option>
                  <option value="DINNER">DINNER</option>
                  <option value="EVENING_SNACK">EVENING SNACK</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="exampleFormControlSelect1">MealChosen:</label>
                  <select name="mealChosen" class="form-control" id="exampleFormControlSelect1">
                   {% for list in meal_list %}
                    <option>{{ list.title }}</option>
                   {% endfor %}
                  </select>
                </div>

                

                {% comment %} <div class="form-group mb-0">
                  <label class="form-control-label d-block mb-3"
                    >Status color</label
                  >
                  <div
                    class="btn-group btn-group-toggle btn-group-colors event-tag"
                    data-toggle="buttons"
                  >
                    <label class="btn bg-info active"
                      ><input
                        type="radio"
                        name="event-tag"
                        value="bg-info"
                        checked
                    /></label>
                    <label class="btn bg-warning"
                      ><input type="radio" name="event-tag" value="bg-warning"
                    /></label>
                    <label class="btn bg-danger"
                      ><input type="radio" name="event-tag" value="bg-danger"
                    /></label>
                    <label class="btn bg-success"
                      ><input type="radio" name="event-tag" value="bg-success"
                    /></label>
                    <label class="btn bg-secondary"
                      ><input type="radio" name="event-tag" value="bg-default"
                    /></label>
                    <label class="btn bg-primary"
                      ><input type="radio" name="event-tag" value="bg-primary"
                    /></label>
                  </div>
                </div> {% endcomment %}
                 <!-- Date -->
                <input type="hidden" class="new-event--start" />
            <input type="hidden"  class="new-event--end" />
            <!-- Date -->
              </form>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-sm btn-link"
                data-dismiss="modal"
              >
                Cancel
              </button>
              <button
                type="button"
                class="btn btn-sm btn-primary rounded-pill float-right new-event--add"
              >
                Create event
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- Modal - Edit event -->
      <div
        class="modal fade"
        id="edit-event"
        tabindex="-1"
        role="dialog"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
              <form class="edit-event--form">
                <div class="form-group">
                  <label class="form-control-label">Event title</label>
                  <input
                    type="text"
                    class="form-control form-control-alternative edit-event--title"
                    placeholder="Event Title"
                  />
                </div>
                <div class="form-group">
                  <label class="form-control-label d-block mb-3"
                    >Status color</label
                  >
                  <div
                    class="btn-group btn-group-toggle btn-group-colors event-tag mb-0"
                    data-toggle="buttons"
                  >
                    <label class="btn bg-info active"
                      ><input
                        type="radio"
                        name="event-tag"
                        value="bg-info"
                        checked
                    /></label>
                    <label class="btn bg-warning"
                      ><input type="radio" name="event-tag" value="bg-warning"
                    /></label>
                    <label class="btn bg-danger"
                      ><input type="radio" name="event-tag" value="bg-danger"
                    /></label>
                    <label class="btn bg-success"
                      ><input type="radio" name="event-tag" value="bg-success"
                    /></label>
                    <label class="btn bg-secondary"
                      ><input type="radio" name="event-tag" value="bg-default"
                    /></label>
                    <label class="btn bg-primary"
                      ><input type="radio" name="event-tag" value="bg-primary"
                    /></label>
                  </div>
                </div>
                <div class="form-group">
                  <label class="form-control-label">Description</label>
                  <textarea
                    class="form-control form-control-alternative edit-event--description textarea-autosize"
                    placeholder="Event Desctiption"
                  ></textarea>
                  <i class="form-group--bar"></i>
                </div>
                <input type="hidden" class="edit-event--id" />
              </form>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-sm btn-link"
                data-dismiss="modal"
              >
                Cancel
              </button>
              <button
                type="button"
                class="btn btn-sm btn-primary rounded-pill float-right"
                data-calendar="update"
              >
                Update
              </button>
              <button
                type="button"
                class="btn btn-sm btn-danger rounded-pill float-right"
                data-calendar="delete"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/partials/_dashboard_days.html
<div class="row">
          <div class="col-lg-4">
            <div class="card card-stats h-100">
              <!-- Card body -->
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <h6 class="text-muted mb-1">{{todayIntensity.date | date:"l"}}</h6>
                    <span class="h5 font-weight-bold mb-0">{{todayIntensity.intensity}}</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon bg-gradient-warning text-white rounded-circle icon-shape">
                        <strong>{{todayIntensity.intensity | slice:'1'}}</strong>
                    </div>
                  </div>
                </div>
                <div class="card">
                    <div class="card-body">
                {% for meal in todayMeals%}
                <li class="list-unstyled" style="text-decoration: none;"><a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">{{meal.mealChosen.title}}</a></li>
                {%endfor%}
                </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 ">
            <div class="card card-stats h-100 ">
              <!-- Card body -->
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <h6 class="text-muted mb-1">{{secondDayIntensity.date | date:"l"}}</h6>
                    <span class="h5 font-weight-bold mb-0">{{secondDayIntensity.intensity}}</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon bg-gradient-warning text-white rounded-circle icon-shape">
                        <strong>{{secondDayIntensity.intensity | slice:'1'}}</strong>
                    </div>
                  </div>
                </div>
                <div>
                {% for meal in secondDayMeals%}
                <li class="list-unstyled" style="text-decoration: none;"><a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">{{meal.mealChosen.title}}</a></li>
                {%endfor%}
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 ">
            <div class="card card-stats h-100 ">
              <!-- Card body -->
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <h6 class="text-muted mb-1">{{thirdDayIntensity.date | date:"l"}}</h6>
                    <span class="h5 font-weight-bold mb-0">{{thirdDayIntensity.intensity}}</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon bg-gradient-warning text-white rounded-circle icon-shape">
                        <strong>{{thirdDayIntensity.intensity | slice:'1'}}</strong>
                    </div>
                  </div>
                </div>
                {% for meal in thirdDayMeals%}
                <li class="list-unstyled" style="text-decoration: none;"><a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">{{meal.mealChosen.title}}</a></li>
                {%endfor%}
              </div>
            </div>
          </div>
        </div>

templates/partials/_dashboard_tomorrow.html
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">Tomorrow's Meals</h5>
        <span class="text-muted text-sm">Plan ahead if you need</span>
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for meal in secondDayMeals%}
            <a href="/recipe/{{meal.mealChosen.id}}"  target="_blank" rel="noopener noreferrer" class="list-group-item list-group-item-action active">
            {{meal.mealPosition}}: {{meal.mealChosen.title}}
            </a>
            {%endfor%}
          </ul>
    </div>
    <div class="card-footer text-center">
        <a href="/mealplanview/" role="button" class="btn btn-soft-primary">
           View All Planned Meals 
        </a>
        &nbsp;
        <a href="/cal/calendar/" role="button" class="btn btn-soft-dark">
            Edit Daily Schedule
        </a>
    </div>
</div>

templates/partials/_favorites_widget.html
<div class="card">
    <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h6 class="mb-0">Want Something Different?</h6>
        </div>
        <div class="text-right">
            
        </div>
    </div>
</div>

    <div class="list-group list-group-flush">
    {% for favorite in favorites%}
    
    
    
    
    
    <div class="list-group-item">
        
<div class="media align-items-center">
    <div class="mr-3">
        <img alt="{{favorite.recipe.title}}" src="{{favorite.recipe.image}}" class="avatar  rounded-circle">

    </div>
    <div class="media-body text-limit">
        <h6 class="text-sm d-block text-limit mb-0"></h6>
        <span class="d-block text-sm text-muted">{{favorite.recipe.title}}</span>
    </div>
    <div class="media-body text-right">
        <button onclick="location.href='/recipe/{{favorite.recipe.id}}'" type="button" class="btn btn-sm btn-secondary">View</button>
    </div>
</div>


    </div>
    
    
    
    {% endfor %}
</div>


</div>

templates/partials/_filter_dates_partial.html
      <form action="{% url 'pages:mealplanView' %}" method="POST">
          {%csrf_token%}
          <label for="date"> Beggining Date</label>
          <input class="form-control" type="date" value="{{startdate| date:'Y-m-d'}}" id="date" name="date">
          <label for="enddate"> End Date</label>
          <input class="form-control" type="date" value="{{enddate| date:'Y-m-d'}}" id="enddate" name="enddate"><br>
          
      
          <button class="btn btn-primary" id="submit" type="submit">Adjust Dates</button>
      </form>
     
    

templates/partials/_generate_plan_partial.html
 
      <form action="{% url 'pages:mealplanView' %}" method="POST" id="generate-plan">
        {%csrf_token%}
        <label for="date"> Beggining Date</label>
        <input class="form-control" type="date" id="startdate" name="startdate"><br>
        <label for="enddate"> End Date</label>
        <input class="form-control" type="date" id="enddate" name="enddate"><br>
         
        <br>
        <button class="btn btn-primary" id="submit" type="submit">Submit form</button>
    </form>
    <br>

    <div class="card-footer">
      {% include 'generate/generate_progress.html' %}
    </div>
 

templates/partials/_generate_shopping_list.html
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">Generate Shopping List</h5>
        
    </div>
    <div class="card-body">

        <form action="{% url 'pages:dashboard' %}" method="POST">

            {%csrf_token%}
            <label for="name">Name</label>
            <input class="form-control" type="text" id="name" name="name"><br>
            <label for="date"> Beggining Date</label>
            <input class="form-control" type="date" id="date" name="date"><br>
            <label for="enddate"> End Date</label>
            <input class="form-control" type="date" id="enddate" name="enddate"><br>
             
            <br>
            <button class="btn btn-primary" id="submit" type="submit">Submit form</button>
        </form>
        
    </div>
    <div class="card-footer">
        <div class="row align-items-center">
            <div class="col">

                <span class="h6 mb-0 avatar-content">Incomplete Shopping Lists: </span>

                <span class="h6 mb-0 avatar-content">Your Lists: </span>

            </div>
        </div>
        
        <ul class="list-group">
            {% for list in shoppingLists%}
            <a href='/shoppinglist/{{list.id}}'>
            <li class="list-group-item">{{list.name}}</li>
            </a>
            {% endfor %}
        </ul>
    </div>
    
    
</div>

templates/partials/_generated_meals.html
<div id="meals">
    <div class="list-group list-group-flush">
  
  
        {% for meal in mealPlans %}
        {% if meal.start == date %}
       <div class="list-group-item list-group-item-action">
       
    <div class="media align-items-center">
      <a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer">
      <div class="mr-3">
          <img alt="{{meal.mealChosen.title}}" src="{{meal.mealChosen.image}}" loading=lazy class="avatar  rounded-circle">
    
      </div>
    </a>
    <a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer">
      <div class="media-body">
          <h6 class="text-sm d-block text-limit mb-0">{{meal.mealChosen.title}} id={{meal.id}}</h6>
          <span class="d-block text-sm text-muted"> {{meal.mealPosition}} - {{meal.mealChosen.percentCalories}}% - {{meal.mealChosen.cookingMins}} mins</span>
      </div>
    </a>
      <div id="buttons-lock{{meal.id}}" class="media-body text-right lock-buttons">
    
        {% if meal.saved %}
        <button type="button" data-id="{{meal.id}}" data-status="UNLOCK" class="btn btn-danger btn-sm lock">
          Unlock
        </button>
      </div>
      {%else%}
        <button type="button" data-id="{{meal.id}}" data-status="LOCK" class="btn btn-success btn-sm lock">
          Lock
        </button>
    
    </div>
    
      {%endif %}
      </div>
    </div>
    
      </a>
      
      {%endif %}
      {% endfor %} 
     
      
      
      
     
    </div>
    </div>

</div>


</div>

templates/partials/_ingredient_results.html
<div class="card-wrapper p-3">
    <div id="checklist" class="checklist" data-toggle="dragula">
      {% if items.count > 0 %}
      {% for item in items %}
      <div id=card{{item.id}} class="card border draggable-item shadow-none">
        <div class="px-3 py-2 row align-items-center">
          <div class="col-10">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="del_{{item.id}}">
              <label class="custom-control-label h6 text-sm" for="del_{{item.id}}">{{item.ingredient.description}} &nbsp;  <small>{{item.ingredient.recipe.title}}</small> </label>
            </div>
          </div>
          <div class="col-auto card-meta d-inline-flex align-items-center ml-sm-auto">
            <div class="dropdown" data-toggle="dropdown">
              <a href="#" class="action-item" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-h"></i>
              </a>
              
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      Nothing found!
      {% endif %}
    </div>
    
  </div>

templates/partials/_shoppinglist_manage.html
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">Generate Shopping List</h5>
        
    </div>
    <div class="card-body" id="generate-form">
        <form action="{% url 'pages:generate_shopping_list' %}" method="POST" id="generate-list">
            {%csrf_token%}
            <label for="name">Name</label>
            <input class="form-control" type="text" id="name" name="name"><br>
            <label for="date"> Beggining Date</label>
            <input class="form-control" type="date" id="date" name="date"><br>
            <label for="enddate"> End Date</label>
            <input class="form-control" type="date" id="enddate" name="enddate"><br>
             
            <br>
            <button class="btn btn-primary" id="submit"  data-dismiss="static" type="submit">Submit form</button>
        </form>
      </div>
</div>
<div id="lists">
  {% if shoppingListModal%}
{% for list in shoppingListModal%}
<div class="card card-stats" id="list{{list.id}}">
  <!-- Card body -->
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h6 class="text-muted mb-1">{{list.name}}</h6>
        <span class="text-nowrap">{{list.start}} - {{list.end}}</span>
      </div>
      <div class="col-auto">
        <div class="icon bg-gradient-danger text-white rounded-circle trash icon-shape" data-id="{{list.id}}">
          <i class="fas fa-trash"></i>
        </div>
      </div>
    </div>
    <p class="mt-3 mb-0 text-sm">
     
      
      <span class="h5 font-weight-bold mb-0"> <a href="{%url 'pages:shoppingList' list.id%}"> View List </a></span>
    </p>
  </div>
</div>
{% endfor %}
{%else%}
<div class="card-body">

  No Shopping Lists Right Now. Create one above! 

</div>
{%endif%}
</div>        
   