app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('test/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
    path('cal/', include('cal.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from django.conf.urls import url

app_name = 'pages'

urlpatterns = [
    #path('', views.index, name='index'), 
    path('dashboard/', views.dashboard, name='dashboard'), 
    #path('home/', views.home, name='home'),    
    #path('register', views.register, name='register'),
    #path('login', views.login, name='login'),
    path('calendar/', views.calendar, name='calendar'),
    path('shoppinglist/<int:list_id>/', views.shopping_list, name='shoppingList'),
    path('plan-create/', views.plan_generate, name='plancreate'),
    path('mealplanview/', views.mealplan_view, name='mealplanView'),
    url(r'ajax/dismiss_shopping_list_item/$', views.dismiss_shopping_list_item, name='dismiss_item'),
    url(r'ajax/lock_status/$', views.meal_plan_lock_status, name='meal_plan_lock_status'),
    url(r'ajax/remove_shopping_list/$', views.remove_shopping_list, name='remove_shopping_list'),
    url(r'ajax/generate_shopping_list/$', views.generate_shopping_list, name='generate_shopping_list'),
    url(r'ajax/feedback_meal/$', views.feedback_meal, name='feedback_meal'),

]

templates/pages/addToMealPlan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Test</h1>

{% endblock %}

templates/pages/calendar.html
{%extends 'base.html' %}
{% load static %}
{% block head %}
<script>

    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
      var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth'
      });
      calendar.render();
    });

  </script>
<script>
    




    $(document).ready(function () {
        
        var calendar = $('#calendar').fullCalendar({
            defaultView: 'agendaWeek',
            header: {
                left: 'title',
                center: '',
                right: 'today, prev, next'

            },
            events: [
                {% for event in events %}
                    {
                        title: "{{event.mealPosition}}:" + "{{ event.name}}",
                        start: '{{ event.start|date:"Y-m-d" }}',
                        id: '{{ event.id }}',
                        mealChosen: '{{ event.mealChosen }}',  
                    },
                    {% endfor %}
            ],
            eventColor: '#378006',
            selectable: true,
            selectHelper: true,
            editable: true,
            eventLimit: true,
            select: function (start, end, allDay) {
                var title = prompt("Enter Event Title");
                if (title) {
                    var start = $.fullCalendar.formatDate(start, "Y-MM-DD");
                    var end = $.fullCalendar.formatDate(end, "Y-MM-DD");
                    $.ajax({
                        type: "GET",
                        url: '/add_event',
                        data: {'title': title, 'start': start},
                        dataType: "json",
                        success: function (data) {
                            calendar.fullCalendar('refetchEvents');
                            alert("Added Successfully");
                        },
                        failure: function (data) {
                            alert('There is a problem!!!');
                        }
                    });
                }
            },
            eventResize: function (event) {
                var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
                var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
                var title = event.title;
                var id = event.id;
                $.ajax({
                    type: "GET",
                    url: '/update',
                    data: {'title': title, 'start': start, 'id': id},
                    dataType: "json",
                    success: function (data) {
                        calendar.fullCalendar('refetchEvents');
                        alert('Event Update');
                    },
                    failure: function (data) {
                        alert('There is a problem!!!');
                    }
                });
            },

            eventDrop: function (event) {
                var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD");
                var title = event.title;
                var id = event.id;
                $.ajax({
                    type: "GET",
                    url: '/update',
                    data: {'title': title, 'start': start,'id': id},
                    dataType: "json",
                    success: function (data) {
                        calendar.fullCalendar('refetchEvents');
                        alert('Event Update');
                    },
                    failure: function (data) {
                        alert('There is a problem!!!');
                    }
                });
            },

            eventClick: function (event) {
                if (confirm("Are you sure you want to remove it?")) {
                    var id = event.id;
                    $.ajax({
                        type: "GET",
                        url: '/remove',
                        data: {'id': id},
                        dataType: "json",
                        success: function (data) {
                            calendar.fullCalendar('refetchEvents');
                            alert('Event Removed');
                        },
                        failure: function (data) {
                            alert('There is a problem!!!');
                        }
                    });
                }
            },

        });
    });

</script>
{%endblock%}
{%block content %}
{% include 'partials/_calendar.html'%}

{% endblock %}

{%block js %}



{% endblock %}

templates/pages/display_progress.html
{% extends 'base.html'%}

{%block head %}
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script>
    $(function () {
        var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
        CeleryProgressBar.initProgressBar(progressUrl)
      });
</script>
{%endbock%}

{%block content %}
<div class='progress-wrapper'>
    <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
  </div>
  <div id="progress-bar-message">Waiting for progress to start...</div>
  <div id="celery-result"></div>
{%endblock%}

templates/pages/generate-meal-plan.html
{% extends 'base.html' %}


{% extends 'base.html' %}
{%load static%}


{%block head %}


{%endblock%}


{% block content %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-0">Generate Meal Plan</h5>
        
    </div>
    <div class="card-body">
        <form action="{% url 'plancreate' %}" method="POST">
            {%csrf_token%}
            <label for="date"> Beggining Date</label>
            <input class="form-control" type="date" id="date" name="date"><br>
            <label for="enddate"> End Date</label>
            <input class="form-control" type="date" id="enddate" name="enddate"><br>
             
            <br>
            <button class="btn btn-primary" id="submit" type="submit">Submit form</button>
        </form>
        
    </div>


    <div class="card-footer">
        <div class="row align-items-center">
            <div class="col">
                <span class="h6 mb-0 avatar-content">Incomplete Shopping Lists: </span>
            </div>
        </div>
        <ul class="list-group">
            {% for list in shoppingLists%}
            <li class="list-group-item">{{list.name}}</li>
            {% endfor %}
        </ul>
    </div>

    
    
</div>


{%endblock%}

<div class="container" style="padding-top: 20px;">
	<form action="" method="post" style="display: inline;">
		{% csrf_token %}
		<div class="form-group">
			<div class="input-group mb-3" align="center" style="margin:0 auto;">
			  {{ form.url }}
			  <div class="input-group-append">
				<button class="btn btn-primary" type="submit" style="width:120px;">
					<strong>Download</strong>
				</button>
			  </div>
			</div>
		</div>
		{{ form.errors }}
	</form>
</div>




<div class='progress-wrapper'>
    <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
  </div>
  <div id="progress-bar-message">Waiting for progress to start...</div>
  <div id="celery-result"></div>

{%endblock%}

{% block js %}
<script type="text/javascript">
    function processProgress(progressBarElement, progressBarMessageElement, progress) {
        progressBarElement.style.width = progress.percent + "%";
        var description = progress.description || "Starting download";
        progressBarMessageElement.innerHTML = description;
    }

    function processResult(resultElement, result) {
    if (result.includes("successful")) {
        $( resultElement ).append(
            $('<br>')
        );
        $( resultElement ).append(
            $('<p class="text-center">').text(result)
        );
    }
}


    $(function () {
        var progressUrl = "{% url 'celery_progress:task_status' 'task_id' %}"
        var progressUrl = progressUrl.replace("task_id", response.task_id)
        CeleryProgressBar.initProgressBar(progressUrl);
      
      });
</script>

{% endblock %}

templates/pages/home.html
{% extends 'base.html'%}

{% block content %}
{% include 'partials/_home.html'%}

{% endblock %}

{% block js %}
<script>
    var options = {
        chart: {
          type: 'line'
        },
        series: [{
          name: 'sales',
          data: [30,40,35,50],
          type: 'line',},
          {
            name: 'series2',
            type: 'line',
          data: [30,40,100,50],

        }],
        
        xaxis: {
          categories: [1991,1992,1993,1994]
        }
      }
      
      var chart = new ApexCharts(document.querySelector("#chart"), options);
      
      chart.render();
      
</script>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% for dayNeed in dayNeeds %}
    <h1> Day need {{ dayNeed.id }}</h1>
    {% for option in optionBreakfasts %}
    {% if option.dayNeeds.id == dayNeed.id %}
    <h1>Breakfast </h1>
    <div class="card">
        <img class="card-img-top" src="{{ option.optionImage }}" alt="Card image cap" width="50" height="400">
        <div class="card-body">
            <h5 class="card-title">{{ option.optionTitle }}</h5>
            <p class="card-text">Chosen = {{option.chosen}}</p>
            <a id="chooserecipe" data-chooserecipeid="{{ option.id}}" class="btn btn-sm btn-primary"> Choose this one </a>
        </div>
    </div>
    
    {% else %}
    <div></div>
    {% endif %}
    {% endfor %}

    {% for option in optionLunchs %}
    <h1>Lunch </h1>
    <div class="card">
        <img class="card-img-top" src="{{ option.optionImage }}" alt="Card image cap" width="50" height="400">
        <div class="card-body">
            <h5 class="card-title">{{ option.optionTitle }}</h5>
            <p class="card-text">Chosen = {{option.chosen}}</p>
            <a id="chooserecipe" data-chooserecipeid="{{ option.id}}" class="btn btn-sm btn-primary"> Choose this one </a>
        </div>
    </div>
    {% endfor %}
    
{% endfor %}

{% endblock %}

{% block js %}
<script>
    $('#chooserecipe').click(function(){
        alert('yo')
        fid = $(this).data("chooserecipeid");
        console.log('fid -> ' + fid)
        $.ajax({
          type: 'GET',
          url: `{% url 'ajax_update_breakfast' %}`,
          data: {
            chooserecipeid: fid,
          },
          success: function(response) {
            
            /*$('#table ').load(location.href + ' #table>*', '');*/
          },
          error: function(response) {
            /*alert('Error from Ajax');*/
          }
        })
        /**
        var eid;
        eid = $(this).attr("data-engagmentid");
        $.get('ajax/ajax_change_status', {enagement_id: eid}, function(data){
          $('#refesh_engage').hide();
          alert("did stuff");
        })
        */
      });
    
</script>
{% endblock %}

templates/pages/mealPlanView.html
{% extends 'base.html' %}
{% load static %}
{%block content %}

  <!-- Button trigger modal -->

<script src="{% static 'celery_progress/celery_progress.js' %}"></script>

<!-- Modal -->
        

<!-- Download Form -->


<div class="card-fluid">
  <div class="card-header">
    <div class="card-body">
      <div id="accordion-1" class="accordion accordion-stacked">
    
        <!-- Accordion card 1 -->
        <div class="card">
            <div class="card-header py-4" id="heading-1-1" data-toggle="collapse" role="button" data-target="#collapse-1-1" aria-expanded="false" aria-controls="collapse-1-1">
                <h6 class="mb-0"><i class="fas fa-file-pdf mr-3"></i>Adjust Dates Viewed</h6>
            </div>
            <div id="collapse-1-1" class="collapse" aria-labelledby="heading-1-1" data-parent="#accordion-1">
                <div class="card-body">
                   {% include 'partials/_filter_dates_partial.html' %}
                </div>
            </div>
        </div>
        
        <!-- Accordion card 2 -->
        <div class="card">
            <div class="card-header py-4" id="heading-1-2" data-toggle="collapse" role="button" data-target="#collapse-1-2" aria-expanded="false" aria-controls="collapse-1-2">
                <h6 class="mb-0"><i class="fas fa-lock mr-3"></i>Generate Meal Plan For Multiple Days</h6>
            </div>
            <div id="collapse-1-2" class="collapse" aria-labelledby="heading-1-2" data-parent="#accordion-1">
                <div class="card-body">
                    {% include 'partials/_generate_plan_partial.html'%}
                </div>
            </div>
        </div>
        
        <!-- Accordion card 3 -->
        <div class="card">
            <div class="card-header py-4" id="heading-1-3" data-toggle="collapse" role="button" data-target="#collapse-1-3" aria-expanded="false" aria-controls="collapse-1-3">
                <h6 class="mb-0"><i class="fas fa-credit-card mr-3"></i>Why do some days have no meals? </h6>
            </div>
            <div id="collapse-1-3" class="collapse" aria-labelledby="heading-1-3" data-parent="#accordion-1">
                <div class="card-body">
                    <p>You just need to set your <a href="/cal/calendar">schedule </a> for any days without meals, then click Generate Meal Plan for Multiple Days.</p>
                </div>
            </div>
        </div>
        
    </div>
    </div>
  </div>
</div>





  {% for date in dates %}
    

  <div class="card">
    <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h6 class="mb-0">{{date}}</h6>
        </div>
        <div class="text-right">
            <div class="actions">
              Generate New Meals
                <button data-date="{{date|date:'Y-m-d'}}" class="action-item"><i class="fas fa-sync"></i></button>
              
            </div>
        </div>
    </div>
  </div>
  <div id="refresh{{date|date:'Y-m-d'}}" class="list-group list-group-flush">
  
  
    {% for meal in mealPlans %}
    {% if meal.start == date %}
   <div class="list-group-item list-group-item-action">
   
<div class="media align-items-center">
  <a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer">
  <div class="mr-3">
      <img alt="{{meal.mealChosen.title}}" src="{{meal.mealChosen.image}}" loading=lazy class="avatar  rounded-circle">
  </div>
  
</a>
<a href="/recipe/{{meal.mealChosen.id}}" target="_blank" rel="noopener noreferrer">
  <div class="media-body">
      <h6 class="text-sm d-block text-limit mb-0">{{meal.mealChosen.title}} id={{meal.id}}</h6>
      <span class="d-block text-sm text-muted"> {{meal.mealPosition}} - {{meal.mealChosen.percentCalories}}% - {{meal.mealChosen.cookingMins}} mins</span>
  </div>
  
</a>


  <div id="buttons-lock{{meal.id}}" class="media-body text-right lock-buttons">

    {% if meal.saved %}
    
    <button type="button" data-date="{{date|date:'Y-m-d'}}" data-id="{{meal.id}}" data-status="UNLOCK" class="btn btn-danger btn-sm lock">
      Replace
    </button>
  </div>
  {%else%}
    <button type="button" data-date="{{date|date:'Y-m-d'}}" data-id="{{meal.id}}" data-status="LOCK" class="btn btn-success btn-sm lock">
      Keep
    </button>

</div>

  {%endif %}
  </div>
</div>

  </a>
  
  {%endif %}
  {% endfor %} 
 
  
  
  
 
</div>
</div>
{% endfor %}


</div>
</div>
</div>

{%endblock%}

{%block js %}
<script>
$(document).ready(function(){
  $('.lock').click(function(){
    $this = $(this)
    id = $(this).data('id')
    status = $(this).data('status')
    date = $(this).data('date')
    alert(status)
    $.ajax({
      type: 'POST',
      url: '{% url "pages:meal_plan_lock_status" %}',
      data: {
        'mealId':id,
        'status': status,
      },
      headers: {'X-CSRFToken': '{{ csrf_token }}'},
      
      success: function(response){
        if($this.hasClass('btn-danger')){
        $this.removeClass('btn btn-danger btn-sm lock').addClass('btn btn-success btn-sm lock').removeAttr('data-status')
        .attr('data-status', "LOCK").html('Keep');
        
        }else if ($this.hasClass('btn-success'))
        $this.removeClass('btn btn-success btn-sm lock').addClass('btn btn-danger btn-sm lock').removeAttr('data-status')
        .attr('data-status', "UNLOCK").html('Replace')
      }
    })
  })
})
</script>

<script>
  $(document).ready(function(){
    $('.action-item').click(function(){
      date = $(this).data('date')
      alert(date)
      $.ajax({
        type: 'POST',
        url: '{% url "pages:mealplanView" %}',
        data: {
          'startdate':date,
          'enddate': date,
        },
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
        
        success: function(response){
          setTimeout(function(){
            window.location.reload();
          }, 8000)
          
        }
      })
    })
  })
  </script>




<script>
  $(document).ready(function() {
    $('#generate-plan').submit(function() { 
        
        // catch the form's submit event
        $.ajax({ // create an AJAX call...
            data: $(this).serialize(), // get the form data
            type: $(this).attr('method'), // GET or POST
            url: $(this).attr('action'),
            success: function(data){
             ('#generateModal2').modal('show');
            } // the file to call
        });
    });
});
</script>


{%endblock %}

templates/pages/settings.html
{% extends 'base.html' %}
{% block content %}

{% include 'partials/_billing.html'%}

{% endblock %}

templates/pages/shoppinglist.html
{% extends 'base.html' %}

{% load static %}


{%block content %}




<div class="card">
	<div class="card-header">
		<div class="d-flex justify-content-between align-items-center">
			<div>
				<h6 class="mb-0">Shopping List</h6>
			

	
	
			</div>
			
			<div class="text-right">
				<div class="actions">
					<div class="action-item">
						<i id="search-icon" class="fas fa-search"></i>
						<input id="user-input" placeholder="Search">
					</div>
					<a id="itemclear" class="action-item"><i class="fas fa-sync"></i></a>
				</div>
			</div>
			</div>
		</div>
		
	<div id="replaceable-content">
	{% include 'partials/_ingredient_results.html'%}
	</div>
</div>



			






{% block js %}

<script src="{% static 'libs/dragula/dist/dragula.min.js' %}"></script>

<script>
	$(document).ready(function(){

		$('#itemclear').click(function(){
			var post_arr = [];
	
			// Get checked checkboxes
			$('#checklist input[type=checkbox]').each(function() {
				if (jQuery(this).is(":checked")) {
					var id = this.id;
					var splitid = id.split('_');
					var postid = splitid[1];
	
					post_arr.push(postid);
					
				}
			});
	
			if(post_arr.length > 0){
					console.log(post_arr);
					var isDelete = confirm("You sure have these?");
					if (isDelete == true) {
						 // AJAX Request
						 $.ajax({
							url:'{% url "pages:dismiss_item" %}',
								type: 'POST',
								data: { 
									'post_id': JSON.stringify(post_arr),
								},
								headers: {'X-CSRFToken': '{{ csrf_token }}'},
								
								success: function(response){
									 $.each(post_arr, function( i,l ){
							
											 $("#card"+l).remove();
									 });
								}
						 });
					} 
			} 
		});
	 
	});
</script>
<script>
const user_input = $("#user-input")
const search_icon = $('#search-icon')
const list_div = $('#replaceable-content')
const endpoint = '{% url "pages:shoppingList" shoppingList.id %}'
const delay_by_in_ms = 700
let scheduled_function = false

let ajax_call = function (endpoint, request_parameters) {
		$.getJSON(endpoint, request_parameters)
				.done(response => {
						// fade out the artists_div, then:
						list_div.fadeTo('slow', 0).promise().then(() => {
								// replace the HTML contents
								list_div.html(response['html_from_view'])
								// fade-in the div with new contents
								list_div.fadeTo('slow', 1)
								// stop animating search icon
								search_icon.removeClass('blink')
						})
				})
}


user_input.on('keyup', function () {

		const request_parameters = {
				q: $(this).val() // value of user_input: the HTML element with ID user-input
		}

		// start animating the search icon with the CSS class
		search_icon.addClass('blink')

		// if scheduled_function is NOT false, cancel the execution of the function
		if (scheduled_function) {
				clearTimeout(scheduled_function)
		}

		// setTimeout returns the ID of the function to be executed
		scheduled_function = setTimeout(ajax_call, delay_by_in_ms, endpoint, request_parameters)
})



</script>




{% endblock %}



{% endblock %}






<!--
<table> 
	<tr>
		<th> ID </th>
		<th> Description</th>
		<th>Recipe</th>
		
	</tr>
	
	{% for item in items %}
	<tr>
	<th> {{item.ingredient.id}} </th>
	<th> {{item.ingredient.description}}</th>
	<th>{{item.ingredient.recipe.title}}</th>

	</tr>
	{%endfor%}
</table>
-->