app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('test/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
    path('cal/', include('cal.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views
from django.conf.urls import url

app_name = 'pages'

urlpatterns = [
    #path('', views.index, name='index'), 
    path('dashboard/', views.dashboard, name='dashboard'), 
    #path('home/', views.home, name='home'),    
    #path('register', views.register, name='register'),
    #path('login', views.login, name='login'),
    path('calendar/', views.calendar, name='calendar'),
    path('shoppinglist/<int:list_id>/', views.shopping_list, name='shoppingList'),
    path('plan-create/', views.plan_generate, name='plancreate'),
    path('mealplanview/', views.mealplan_view, name='mealplanView'),
    url(r'ajax/dismiss_shopping_list_item/$', views.dismiss_shopping_list_item, name='dismiss_item'),
    url(r'ajax/lock_status/$', views.meal_plan_lock_status, name='meal_plan_lock_status'),
    url(r'ajax/remove_shopping_list/$', views.remove_shopping_list, name='remove_shopping_list'),
    url(r'ajax/generate_shopping_list/$', views.generate_shopping_list, name='generate_shopping_list'),
    url(r'ajax/feedback_meal/$', views.feedback_meal, name='feedback_meal'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Purpose Application UI is the following chapter we've finished in order to create a complete and robust solution next to the already known Purpose Website UI.">
  <meta name="author" content="Webpixels">
  <title>{%block title%} {%endblock%}</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'js/all.min.css' %}"><!-- Page CSS -->
  <link rel="stylesheet" href="{% static 'js/fullcalendar.min.css' %}">
  <link rel="stylesheet" href="{% static 'js/sweetalert2.min.css' %}">
  <!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'css/purpose.css' %}" id="stylesheet">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
  <script src="https://js.stripe.com/v3/"></script>
  <!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'css/purpose.css' %}" id="stylesheet">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  
  {% block head %}
  {% endblock %}
  
<style>
  .navbar-icon-top .navbar-nav .nav-link > .fa {
    position: relative;
    width: 36px;
    font-size: 24px;
  }
  
  .navbar-icon-top .navbar-nav .nav-link > .fa > .badge {
    font-size: 0.75rem;
    position: absolute;
    right: 0;
    font-family: sans-serif;
  }
  
  .navbar-icon-top .navbar-nav .nav-link > .fa {
    top: 3px;
    line-height: 12px;
  }
  
  .navbar-icon-top .navbar-nav .nav-link > .fa > .badge {
    top: -10px;
  }
  
  @media (min-width: 576px) {
    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }
  
    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }
  
    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }
  
  @media (min-width: 768px) {
    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }
  
    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }
  
    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }
  
  @media (min-width: 992px) {
    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }
  
    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }
  
    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }
  
  @media (min-width: 1200px) {
    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }
  
    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }
  
    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }
  


</style>

</head>

<body class="application application-offset">
    

    <div class="container-fluid container-application">
        <!-- Sidenav -->
        
        <!-- Content -->
        <div class="main-content position-relative">
          <!-- Main nav -->
          <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/dashboard/">
                    <i class="fa fa-home"></i>
                    Home
                    <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/mealplanview">
                    <i class="fa fa-utensils">
                      
                    </i>
                    Meals
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="modal" data-target="#shoppingListModal">
                    <i class="fa fa-list">
                    </i>
                    Shopping Lists
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/cal/calendar/">
                    <i class="fa fa-calendar">
                     
                    </i>
                    Schedule
                  </a>
                </li>
                
              </ul>
              <ul class="navbar-nav ">
                <li class="nav-item">
                  <a class="nav-link" href="/recipe/recipe_search">
                    <i class="fa fa-search">
                     
                    </i>
                    Recipe Search
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user">
                   
                    </i>
                    {{user.name}}
                  </a>
                  <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right dropdown-menu-arrow">
                    <h6 class="dropdown-header px-0">Hi, {{ user.name }}!</h6>
                    <a href="#!" class="dropdown-item">
                      <i class="fas fa-user"></i>
                      <span>My profile</span>
                    </a>
                    <a href="#!" class="dropdown-item">
                      <i class="fas fa-cog"></i>
                      <span>Settings</span>
                    </a>
                    <a href="{% url 'cart' %}" class="dropdown-item">
                      <i class="fas fa-credit-card"></i>
                      <span>Billing</span>
                    </a>
                    <a href="#!" class="dropdown-item">
                      <i class="fas fa-tasks"></i>
                      <span>Activity</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'logout' %}" class="dropdown-item">
                      <i class="fas fa-sign-out-alt"></i>
                      <span>Logout</span>
                    </a>
                  </div>
                </li>
              </ul>
              
            </div>
          </nav>
          
          <!-- Omnisearch -->

              
          <div class="modal fade" id="shoppingListModal" tabindex="-1" role="dialog" aria-labelledby="shoppingListModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header style=flex-direction:column;">
                  <h5 class="modal-title" id="exampleModalLabel">Manage Shopping Lists</h5><br>
                  
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body" id="modal-body">

                  {% include 'partials/_shoppinglist_manage.html' %}
                </div>
                <div class="modal-footer">
                 
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>


{% block content %}


{% endblock %}
<div class="footer pt-5 pb-4 footer-light" id="footer-main">
    <div class="row text-center text-sm-left align-items-sm-center">
      <div class="col-sm-6">
        <p class="text-sm mb-0">&copy; 2019 <a href="https://webpixels.io" class="h6 text-sm" target="_blank">Webpixels</a>. All rights reserved.</p>
      </div>
      <div class="col-sm-6 mb-md-0">
        <ul class="nav justify-content-center justify-content-md-end">
          <li class="nav-item dropdown border-right">
            <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img alt="Image placeholder" src="{% static 'img/icons/flags/ro.svg' %}">
              <span class="h6 text-sm mb-0">RO</span>
            </a>
            <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
              <a href="#" class="dropdown-item"><img alt="Image placeholder" src="{% static 'img/icons/flags/es.svg' %}" class="mr-2">Spanish</a>
              <a href="#" class="dropdown-item"><img alt="Image placeholder" src="{% static 'img/icons/flags/us.svg' %}" class="mr-2">English</a>
              <a href="#" class="dropdown-item"><img alt="Image placeholder" src="{% static 'img/icons/flags/gr.svg' %}" class="mr-2">Greek</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Support</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Terms</a>
          </li>
          <li class="nav-item">
            <a class="nav-link pr-0" href="#">Privacy</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

 <!-- Scripts -->
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'js/purpose.core.js' %}"></script>
  <!-- Page JS -->
  <script src="{% static 'js/progressbar.min.js' %}"></script>
  <script src="{% static 'js/apexcharts.min.js' %}"></script>
  <script src="{% static 'js/moment.min.js' %}"></script>
  <script src="{% static 'js/fullcalendar.min.js' %}"></script>
  <script src="{% static 'js/sweetalert2.min.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'js/purpose.js' %}"></script>
<script src="{% static 'js/demo.js' %}"></script>


<script>
  $(document).ready(function() {
    $('#generate-list').submit(function() { 
        // catch the form's submit event
        $.ajax({ // create an AJAX call...
            data: $(this).serialize(), // get the form data
            type: $(this).attr('method'), // GET or POST
            url: $(this).attr('action'), // the file to call
            success: function(response) { // on success..
               
              window.location = '/shoppinglist/' + response 
            }
        });
        return false;
    });
});




</script>


<script>
  $(document).ready(function(){
    $('.trash').click(function(){
     
      id = $(this).data('id')
      $.ajax({
        type: 'POST',
        url: "{% url 'pages:remove_shopping_list' %}",
        data:{
          'listId':id, 
      },
      headers: {'X-CSRFToken': '{{ csrf_token }}'},
      success: function(response){
        $('#list'+ id).remove();
   

      }
      })
    })
  })



</script>


  <!-- Demo JS - remove it when starting your project -->
  {% block js %}
  {% endblock %}
  {% block progress_bar_js %}{% endblock progress_bar_js %}
</body>

</html>

templates/notloggedinbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Purpose Application UI is the following chapter we've finished in order to create a complete and robust solution next to the already known Purpose Website UI.">
  <meta name="author" content="Webpixels">
  <title>Purpose – Application UI Kit</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'libs/@fortawesome/fontawesome-free/css/all.min.css' %}"><!-- Page CSS -->
  <link rel="stylesheet" href="{% static 'libs/fullcalendar/dist/fullcalendar.min.css' %}">
  <!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'css/purpose.css' %}" id="stylesheet">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
 

  
</head>

<body class="application application-offset">
    

    {% block content %}

    {% endblock %}
 <!-- Scripts -->
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'js/purpose.core.js' %}"></script>
  <!-- Page JS -->
  <script src="{% static 'libs/progressbar.js/dist/progressbar.min.js' %}"></script>
  <script src="{% static 'libs/apexcharts/dist/apexcharts.min.js' %}"></script>
  <script src="{% static 'libs/moment/min/moment.min.js' %}"></script>
  <script src="{% static 'libs/fullcalendar/dist/fullcalendar.min.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'js/purpose.js' %}"></script>

  <script type="text/javascript" src="{% static 'jquery-3.5.1.min.js' %}"></script>

  <!-- Demo JS - remove it when starting your project -->
  {% block js %}
  {% endblock %}
</body>

</html>