app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('test/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
    path('cal/', include('cal.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.day_intensity, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.day_intensity, name='event_edit'),
]

cal/models.py
from django.db import models

# Create your models here.

cal/forms.py
from django.forms import ModelForm, DateInput
from recipes.models import DayIntensity

class DayIntensityForm(ModelForm):
  class Meta:
    model = DayIntensity
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'date': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
    }
    fields = ['date', 'intensity', 'busyDay', 'needBreakfast', 'needAmSnack', 'needLunch',
    'needPmSnack', 'needDinner', 'repeatMeals']


    labels = {
      'date': 'For Date',
      'intensity': 'Activity Level',
      'busyDay': 'Busy Day (Short on Time?)',
      'needBreakfast': 'Plan Breakfast',
      'needAmSnack': 'Plan Morning Snack',
      'needLunch': 'Plan Lunch',
      'needPmSnack': 'Plan Afternoon Snack',
      'needDinner': 'Plan Dinner',
      'repeatMeals': 'Repeat Meals?'
    }

  def __init__(self, *args, **kwargs):
    super(DayIntensityForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['date'].input_formats = ('%Y-%m-%d',)
    

cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from django.views import generic
from django.utils.safestring import mark_safe
from django.http import JsonResponse


from recipes.models import *
from .utils import Calendar
import calendar
from .forms import DayIntensityForm

# Create your views here.

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    
    model = DayIntensity
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shoppingListModal = ShoppingList.objects.filter(user=self.request.user, completed=False, delete=False)
        context['shoppingListModal'] = shoppingListModal
        # use today's date for the calendar
        newd = get_date(self.request.GET.get('month', None))
        if newd:
            d = newd
        else: 
            d = get_date(self.request.GET.get('day'))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)

        newd = get_date(self.request.GET.get('month', None))
        print('newd' + str(newd))
        context['prev_month'] = prev_month(newd)
        context['next_month'] = next_month(newd)
        context['form'] = DayIntensityForm
        return context


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    print(month)
    return month

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def day_intensity(request, event_id=None):
    instance = DayIntensity()
    print(event_id)
    if event_id:
        instance = get_object_or_404(DayIntensity, pk=event_id)
    else:
        instance = DayIntensity()
    
    form = DayIntensityForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        day = form.save(commit=False)
        day.user = request.user
        day.save()
        
        

        return HttpResponseRedirect(reverse('cal:calendar'))
    return HttpResponse(form.as_p())

templates/cal/base.html
{%load static %}

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{'% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>
    {%block content %}
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

    {% block js%}
    {% endblock %}

templates/cal/calendar.html
{% extends 'base.html' %}
{%block head %}
<style>
    .calendar {
        width: 98%;
        margin: auto;
        font-size: 13px;
        display: inline-block;
      }
      
      .calendar tr, .calendar td {
        border: 0px solid black;
      }
      
      .calendar th {
        padding: 10px;
        text-align: center;
        font-size: 18px;
      }
      
      .calendar td {
        width: 200px;
        height: 150px;
        padding: 20px 0px 0px 5px;
      }
      
      .month {
        font-size: 25px;
      }
      
      .date {
        font-size: 16px;
      }
      
      ul {
        height: 100%;
        padding: 0px 5px 0px 20px;
      }
      
      
      .left {
        float: left;
      }
      
      .right {
        float: right;
      }
      
    
      
      .clearfix {
        margin: 15px;
      }
</style>
{%endblock%}


{% block content %}
<div class=card>
    <div class="card-header">
</div>

<div class="clearfix">
	<a class="btn btn-primary left"  href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-primary right" style="margin: 0%;" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<button class="btn btn-primary right" style="margin-right: 2%;" data-toggle="modal" data-target="#addintensity1"> New Event </button>
</div>
{{ calendar }}
</table>
</div>


<!-- Add Intensity Modal-->
<div class="modal fade" id="addintensity1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <!-- Modal body -->
        <div class="modal-body">
            <form method="post" action="{% url 'cal:event_new' %}">
                {% csrf_token %}
                <table class="form form-table">
                  {{ form }}
                  <tr><td colspan="2"></td></tr>
                </table>
             
        </div>
        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="submit" class="btn btn-info right"> Submit </button>
        </form>
        </div>
      </div>
    </div>
  </div>


  <div class="modal fade" id="eventEditModal" tabindex="-1" role="dialog" aria-labelledby="editProductModalFormLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <form class="form" method="post" id="edit_product_form" >
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editProductModalFormLabel">Edit Day</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <div id='showForm'></div>
            </div>
            <div class="modal-footer">
              <input type="submit" class="btn btn-primary" value="Submit!">
            </div>
          </div>
    </form>
    </div>
  </div>




{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>

<script>
    $(document).ready(function (){
        $('.edit').click(function(){
            id = $(this).data('id')
            $('#eventEditModal').modal('show');
            $.ajax({
                type: 'GET',
                url: '/cal/event/edit/'+id,
                success: function(res) {
                $("#showForm").html(res);
                $("#edit_product_form").attr('action', '/cal/event/edit/'+id +'/')
            }
            })
        });
        
        }
    )
</script>

{%endblock%}

templates/cal/intensity.html
{% extends 'base.html' %}

{% block head %}
<style>
    .form {
        margin: auto;
      }
      
      .form input, .form select, .form textarea {
        border-radius: 5px;
        border: 1px solid #17a2b8;
        outline: none;
        background: none;
        padding: 5px;
        width: 100%;
      }
</style>
{% endblock %}


{% block content %}
<div class="card">
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
  </div>
  
  <form method="post">
    {% csrf_token %}
    <table class="form form-table">
      {{ form }}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
    </table>
  </form>
</div>

{% endblock %}